name: Build and Deploy to YC

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Yandex Container Registry
      uses: docker/login-action@v1
      with:
        registry: cr.yandex
        username: ${{ secrets.YANDEX_CLOUD_ID }}
        password: ${{ secrets.YANDEX_CLOUD_SECRET }}
    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cr.yandex/${{ secrets.YANDEX_CLOUD_REGISTRY }}/your-repo/image-app:${{ github.sha }}
    - name: Apply K8S manifests
      run: |
        kubectl apply -f k8s/
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
